### ISSUE TITLE
Version 0.8.0: undefined is not a function in node_modules/node-xlsx/lib/index.js:46:57

### ISSUE THREAD

**Issue by thomasuh** [mgcrea/node-xlsx#43]
I think the method signature of the build method did not change. But since the update to 0.7.1 Version of node-xlsx i always get the error:  undefined is not a function in node_modules/node-xlsx/lib/index.js:46:57

using version 0.6.0 the export works pretty fine....

Any thoughts on this?

**Comment by andyhu** [comment]
Instead of using `import xlsx from 'node-xlsx';`, you can try `import { build } from 'node-xlsx';`. That should solve the issue.

**Comment by mgcrea** [comment]
Also if you're using require, you probably now have to:

```
var xlsx = require('node-xlsx').default;
```

**Comment by andyhu** [comment]
@mgcrea Could you please add babel-plugin-add-module-exports plugin? So `.default` is not needed in a normal require

**Comment by mgcrea** [comment]
@andyhu unfortunately this plugin won't work as I export `{parse, build}` (only works if you only export default).
